package add.entidad;
// Generated 24 ene. 2022 21:19:42 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name = "genero", catalog = "videojuegos")
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
public class Genero implements java.io.Serializable {

	private Integer idGenero;
	private String tipo;
	private Set<Videojuego> videojuegos = new HashSet<Videojuego>(0);

	public Genero() {
	}

	public Genero(String tipo) {
		this.tipo = tipo;
	}

	public Genero(String tipo, Set<Videojuego> videojuegos) {
		this.tipo = tipo;
		this.videojuegos = videojuegos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_genero", unique = true, nullable = false)
	public Integer getIdGenero() {
		return this.idGenero;
	}

	public void setIdGenero(Integer idGenero) {
		this.idGenero = idGenero;
	}

	@Column(name = "tipo", nullable = false, length = 20)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinTable(name = "generojuego", catalog = "videojuegos", joinColumns = {
			@JoinColumn(name = "id_genero", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_videojuego", nullable = false, updatable = false) })
	public Set<Videojuego> getVideojuegos() {
		return this.videojuegos;
	}

	public void setVideojuegos(Set<Videojuego> videojuegos) {
		this.videojuegos = videojuegos;
	}

}
