package add.entidad;
// Generated 29 ene. 2022 16:29:30 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Plataforma generated by hbm2java
 */
@Entity
@Table(name = "plataforma", catalog = "videojuegos")
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
public class Plataforma implements java.io.Serializable {

	private Integer idPlataforma;
	private String nombre;
	private Set<Videojuego> videojuegos = new HashSet<Videojuego>(0);

	public Plataforma() {
	}

	public Plataforma(String nombre) {
		this.nombre = nombre;
	}

	public Plataforma(String nombre, Set<Videojuego> videojuegos) {
		this.nombre = nombre;
		this.videojuegos = videojuegos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_plataforma", unique = true, nullable = false)
	public Integer getIdPlataforma() {
		return this.idPlataforma;
	}

	public void setIdPlataforma(Integer idPlataforma) {
		this.idPlataforma = idPlataforma;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinTable(name = "plataformajuego", catalog = "videojuegos", joinColumns = {
			@JoinColumn(name = "id_plataforma", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_videojuego", nullable = false, updatable = false) })
	public Set<Videojuego> getVideojuegos() {
		return this.videojuegos;
	}

	public void setVideojuegos(Set<Videojuego> videojuegos) {
		this.videojuegos = videojuegos;
	}

}
