package add.entidad;
// Generated 29 ene. 2022 16:29:30 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;



/**
 * Videojuego generated by hbm2java
 */
@Entity
@Table(name = "videojuego", catalog = "videojuegos")
public class Videojuego implements java.io.Serializable {

	private Integer id;
	private Company company;
	private Genero genero;
	private String titulo;
	private double precio;
	private Set<Plataforma> plataformas = new HashSet<Plataforma>(0);

	public Videojuego() {
	}

	public Videojuego(Company company, Genero genero, String titulo, double precio) {
		this.company = company;
		this.genero = genero;
		this.titulo = titulo;
		this.precio = precio;
	}

	public Videojuego(Company company, Genero genero, String titulo, double precio, Set<Plataforma> plataformas) {
		this.company = company;
		this.genero = genero;
		this.titulo = titulo;
		this.precio = precio;
		this.plataformas = plataformas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "company", nullable = false)
	
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumn(name = "genero", nullable = false)
	
	public Genero getGenero() {
		return this.genero;
	}

	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	@Column(name = "titulo", nullable = false, length = 30)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}


	@ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "plataformajuego", catalog = "videojuegos", joinColumns = {
            @JoinColumn(name = "id_videojuego", nullable = false, updatable = false) }, inverseJoinColumns = {
                    @JoinColumn(name = "id_plataforma", nullable = false, updatable = false) })
	public Set<Plataforma> getPlataformas() {
		return this.plataformas;
	}

	public void setPlataformas(Set<Plataforma> plataformas) {
		this.plataformas = plataformas;
	}

}
